version: '3.1'

services:
  db:
    image: postgres:11.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
